// <auto-generated />
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using VertexCommerce.Modules.Orders.Persistence;

#nullable disable

namespace VertexCommerce.Modules.Orders.Persistence.Migrations
{
    [DbContext(typeof(OrdersDbContext))]
    [Migration("20260920054811_RefactorShippingSettingsToMoneyVO")]
    partial class RefactorShippingSettingsToMoneyVO
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("orders")
                .HasAnnotation("ProductVersion", "9.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("VertexCommerce.Modules.Orders.Domain.Entities.Order", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("CancellationReason")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<DateTime?>("CancelledAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("ConfirmedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("CustomerId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("DeliveredAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("ExpiresAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<string>("Notes")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<string>("PaymentStatus")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<DateTime?>("ProcessingAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ReceiptImagePath")
                        .HasColumnType("text");

                    b.Property<DateTime?>("ShippedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("TrackingNumber")
                        .HasMaxLength(100)
                        .IsUnicode(true)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("TrackingNumber")
                        .IsFixedLength(false);

                    b.Property<string>("TransactionReference")
                        .HasColumnType("text");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.ComplexProperty<Dictionary<string, object>>("BillingAddress", "VertexCommerce.Modules.Orders.Domain.Entities.Order.BillingAddress#Address", b1 =>
                        {
                            b1.Property<string>("Label")
                                .HasMaxLength(50)
                                .IsUnicode(true)
                                .HasColumnType("character varying(50)")
                                .HasColumnName("BillingLabel")
                                .IsFixedLength(false);

                            b1.ComplexProperty<Dictionary<string, object>>("City", "VertexCommerce.Modules.Orders.Domain.Entities.Order.BillingAddress#Address.City#City", b2 =>
                                {
                                    b2.Property<string>("Value")
                                        .IsRequired()
                                        .HasMaxLength(100)
                                        .IsUnicode(true)
                                        .HasColumnType("character varying(100)")
                                        .HasColumnName("BillingCity")
                                        .IsFixedLength(false);
                                });

                            b1.ComplexProperty<Dictionary<string, object>>("Location", "VertexCommerce.Modules.Orders.Domain.Entities.Order.BillingAddress#Address.Location#GeoLocation", b2 =>
                                {
                                    b2.Property<decimal>("Latitude")
                                        .HasPrecision(9, 6)
                                        .HasColumnType("numeric(9,6)")
                                        .HasColumnName("BillingLatitude");

                                    b2.Property<decimal>("Longitude")
                                        .HasPrecision(9, 6)
                                        .HasColumnType("numeric(9,6)")
                                        .HasColumnName("BillingLongitude");
                                });

                            b1.ComplexProperty<Dictionary<string, object>>("PostalAddress", "VertexCommerce.Modules.Orders.Domain.Entities.Order.BillingAddress#Address.PostalAddress#PostalAddress", b2 =>
                                {
                                    b2.Property<string>("Value")
                                        .IsRequired()
                                        .HasMaxLength(500)
                                        .IsUnicode(true)
                                        .HasColumnType("character varying(500)")
                                        .HasColumnName("BillingPostalAddress")
                                        .IsFixedLength(false);
                                });

                            b1.ComplexProperty<Dictionary<string, object>>("PostalCode", "VertexCommerce.Modules.Orders.Domain.Entities.Order.BillingAddress#Address.PostalCode#PostalCode", b2 =>
                                {
                                    b2.Property<string>("Value")
                                        .IsRequired()
                                        .HasMaxLength(10)
                                        .IsUnicode(false)
                                        .HasColumnType("character varying(10)")
                                        .HasColumnName("BillingPostalCode")
                                        .IsFixedLength(false);
                                });

                            b1.ComplexProperty<Dictionary<string, object>>("Province", "VertexCommerce.Modules.Orders.Domain.Entities.Order.BillingAddress#Address.Province#Province", b2 =>
                                {
                                    b2.Property<string>("Value")
                                        .IsRequired()
                                        .HasMaxLength(100)
                                        .IsUnicode(true)
                                        .HasColumnType("character varying(100)")
                                        .HasColumnName("BillingProvince")
                                        .IsFixedLength(false);
                                });
                        });

                    b.ComplexProperty<Dictionary<string, object>>("CustomerPhoneNumber", "VertexCommerce.Modules.Orders.Domain.Entities.Order.CustomerPhoneNumber#PhoneNumber", b1 =>
                        {
                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasMaxLength(20)
                                .IsUnicode(false)
                                .HasColumnType("character varying(20)")
                                .HasColumnName("CustomerPhoneNumber")
                                .IsFixedLength(false);
                        });

                    b.ComplexProperty<Dictionary<string, object>>("OrderNumber", "VertexCommerce.Modules.Orders.Domain.Entities.Order.OrderNumber#OrderNumber", b1 =>
                        {
                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasMaxLength(50)
                                .IsUnicode(true)
                                .HasColumnType("character varying(50)")
                                .HasColumnName("OrderNumber")
                                .IsFixedLength(false);
                        });

                    b.ComplexProperty<Dictionary<string, object>>("ShippingAddress", "VertexCommerce.Modules.Orders.Domain.Entities.Order.ShippingAddress#Address", b1 =>
                        {
                            b1.Property<string>("Label")
                                .HasMaxLength(50)
                                .IsUnicode(true)
                                .HasColumnType("character varying(50)")
                                .HasColumnName("ShippingLabel")
                                .IsFixedLength(false);

                            b1.ComplexProperty<Dictionary<string, object>>("City", "VertexCommerce.Modules.Orders.Domain.Entities.Order.ShippingAddress#Address.City#City", b2 =>
                                {
                                    b2.Property<string>("Value")
                                        .IsRequired()
                                        .HasMaxLength(100)
                                        .IsUnicode(true)
                                        .HasColumnType("character varying(100)")
                                        .HasColumnName("ShippingCity")
                                        .IsFixedLength(false);
                                });

                            b1.ComplexProperty<Dictionary<string, object>>("Location", "VertexCommerce.Modules.Orders.Domain.Entities.Order.ShippingAddress#Address.Location#GeoLocation", b2 =>
                                {
                                    b2.Property<decimal>("Latitude")
                                        .HasPrecision(9, 6)
                                        .HasColumnType("numeric(9,6)")
                                        .HasColumnName("ShippingLatitude");

                                    b2.Property<decimal>("Longitude")
                                        .HasPrecision(9, 6)
                                        .HasColumnType("numeric(9,6)")
                                        .HasColumnName("ShippingLongitude");
                                });

                            b1.ComplexProperty<Dictionary<string, object>>("PostalAddress", "VertexCommerce.Modules.Orders.Domain.Entities.Order.ShippingAddress#Address.PostalAddress#PostalAddress", b2 =>
                                {
                                    b2.Property<string>("Value")
                                        .IsRequired()
                                        .HasMaxLength(500)
                                        .IsUnicode(true)
                                        .HasColumnType("character varying(500)")
                                        .HasColumnName("ShippingPostalAddress")
                                        .IsFixedLength(false);
                                });

                            b1.ComplexProperty<Dictionary<string, object>>("PostalCode", "VertexCommerce.Modules.Orders.Domain.Entities.Order.ShippingAddress#Address.PostalCode#PostalCode", b2 =>
                                {
                                    b2.Property<string>("Value")
                                        .IsRequired()
                                        .HasMaxLength(10)
                                        .IsUnicode(false)
                                        .HasColumnType("character varying(10)")
                                        .HasColumnName("ShippingPostalCode")
                                        .IsFixedLength(false);
                                });

                            b1.ComplexProperty<Dictionary<string, object>>("Province", "VertexCommerce.Modules.Orders.Domain.Entities.Order.ShippingAddress#Address.Province#Province", b2 =>
                                {
                                    b2.Property<string>("Value")
                                        .IsRequired()
                                        .HasMaxLength(100)
                                        .IsUnicode(true)
                                        .HasColumnType("character varying(100)")
                                        .HasColumnName("ShippingProvince")
                                        .IsFixedLength(false);
                                });
                        });

                    b.ComplexProperty<Dictionary<string, object>>("ShippingCost", "VertexCommerce.Modules.Orders.Domain.Entities.Order.ShippingCost#Money", b1 =>
                        {
                            b1.Property<decimal>("Amount")
                                .HasPrecision(18, 2)
                                .HasColumnType("numeric(18,2)")
                                .HasColumnName("ShippingCost");

                            b1.Property<string>("Currency")
                                .IsRequired()
                                .HasMaxLength(3)
                                .IsUnicode(true)
                                .HasColumnType("character varying(3)")
                                .HasColumnName("ShippingCostCurrency")
                                .IsFixedLength(false);
                        });

                    b.ComplexProperty<Dictionary<string, object>>("SubTotal", "VertexCommerce.Modules.Orders.Domain.Entities.Order.SubTotal#Money", b1 =>
                        {
                            b1.Property<decimal>("Amount")
                                .HasPrecision(18, 2)
                                .HasColumnType("numeric(18,2)")
                                .HasColumnName("SubTotal");

                            b1.Property<string>("Currency")
                                .IsRequired()
                                .HasMaxLength(3)
                                .IsUnicode(true)
                                .HasColumnType("character varying(3)")
                                .HasColumnName("SubTotalCurrency")
                                .IsFixedLength(false);
                        });

                    b.ComplexProperty<Dictionary<string, object>>("Tax", "VertexCommerce.Modules.Orders.Domain.Entities.Order.Tax#Money", b1 =>
                        {
                            b1.Property<decimal>("Amount")
                                .HasPrecision(18, 2)
                                .HasColumnType("numeric(18,2)")
                                .HasColumnName("Tax");

                            b1.Property<string>("Currency")
                                .IsRequired()
                                .HasMaxLength(3)
                                .IsUnicode(true)
                                .HasColumnType("character varying(3)")
                                .HasColumnName("TaxCurrency")
                                .IsFixedLength(false);
                        });

                    b.ComplexProperty<Dictionary<string, object>>("TotalAmount", "VertexCommerce.Modules.Orders.Domain.Entities.Order.TotalAmount#Money", b1 =>
                        {
                            b1.Property<decimal>("Amount")
                                .HasPrecision(18, 2)
                                .HasColumnType("numeric(18,2)")
                                .HasColumnName("TotalAmount");

                            b1.Property<string>("Currency")
                                .IsRequired()
                                .HasMaxLength(3)
                                .IsUnicode(true)
                                .HasColumnType("character varying(3)")
                                .HasColumnName("TotalAmountCurrency")
                                .IsFixedLength(false);
                        });

                    b.HasKey("Id");

                    b.HasIndex("CustomerId");

                    b.ToTable("Orders", "orders");
                });

            modelBuilder.Entity("VertexCommerce.Modules.Orders.Domain.Entities.OrderItem", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<Guid>("OrderId")
                        .HasColumnType("uuid")
                        .HasColumnName("order_id");

                    b.Property<Guid>("ProductId")
                        .HasColumnType("uuid")
                        .HasColumnName("product_id");

                    b.Property<string>("ProductName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("product_name");

                    b.Property<string>("ProductSku")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("product_sku");

                    b.Property<int>("Quantity")
                        .HasColumnType("integer")
                        .HasColumnName("quantity");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<Guid>("VariantId")
                        .HasColumnType("uuid");

                    b.ComplexProperty<Dictionary<string, object>>("UnitPrice", "VertexCommerce.Modules.Orders.Domain.Entities.OrderItem.UnitPrice#Money", b1 =>
                        {
                            b1.Property<decimal>("Amount")
                                .HasPrecision(18, 2)
                                .HasColumnType("numeric(18,2)")
                                .HasColumnName("unit_price_amount");

                            b1.Property<string>("Currency")
                                .IsRequired()
                                .HasMaxLength(3)
                                .IsUnicode(true)
                                .HasColumnType("character varying(3)")
                                .HasColumnName("unit_price_currency")
                                .IsFixedLength(false);
                        });

                    b.HasKey("Id");

                    b.HasIndex("OrderId");

                    b.HasIndex("ProductId");

                    b.ToTable("order_items", "orders");
                });

            modelBuilder.Entity("VertexCommerce.Modules.Orders.Domain.Entities.PaymentSettings", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("AccountHolderName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("AccountNumber")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("BankName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("CardNumber")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<string>("ShabaNumber")
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("IsActive");

                    b.ToTable("PaymentSettings", "orders");
                });

            modelBuilder.Entity("VertexCommerce.Modules.Orders.Domain.Entities.ShippingSettings", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.ComplexProperty<Dictionary<string, object>>("Cost", "VertexCommerce.Modules.Orders.Domain.Entities.ShippingSettings.Cost#Money", b1 =>
                        {
                            b1.Property<decimal>("Amount")
                                .HasPrecision(18, 2)
                                .HasColumnType("numeric(18,2)")
                                .HasColumnName("Cost");

                            b1.Property<string>("Currency")
                                .IsRequired()
                                .HasMaxLength(3)
                                .IsUnicode(true)
                                .HasColumnType("character varying(3)")
                                .HasColumnName("CostCurrency")
                                .IsFixedLength(false);
                        });

                    b.ComplexProperty<Dictionary<string, object>>("FreeShippingThreshold", "VertexCommerce.Modules.Orders.Domain.Entities.ShippingSettings.FreeShippingThreshold#Money", b1 =>
                        {
                            b1.Property<decimal>("Amount")
                                .HasPrecision(18, 2)
                                .HasColumnType("numeric(18,2)")
                                .HasColumnName("FreeShippingThreshold");

                            b1.Property<string>("Currency")
                                .IsRequired()
                                .HasMaxLength(3)
                                .IsUnicode(true)
                                .HasColumnType("character varying(3)")
                                .HasColumnName("FreeShippingThresholdCurrency")
                                .IsFixedLength(false);
                        });

                    b.HasKey("Id");

                    b.HasIndex("IsActive");

                    b.ToTable("ShippingSettings", "orders");
                });

            modelBuilder.Entity("VertexCommerce.Modules.Orders.Domain.Entities.OrderItem", b =>
                {
                    b.HasOne("VertexCommerce.Modules.Orders.Domain.Entities.Order", null)
                        .WithMany("Items")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("VertexCommerce.Modules.Orders.Domain.Entities.Order", b =>
                {
                    b.Navigation("Items");
                });
#pragma warning restore 612, 618
        }
    }
}
