// <auto-generated />
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using VertexCommerce.Modules.Customers.Persistence;

#nullable disable

namespace VertexCommerce.Modules.Customers.Persistence.Migrations
{
    [DbContext(typeof(CustomersDbContext))]
    [Migration("20260907133551_ReplaceCustomerPrimitivesWithValueObjects")]
    partial class ReplaceCustomerPrimitivesWithValueObjects
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("customers")
                .HasAnnotation("ProductVersion", "9.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("VertexCommerce.Modules.Customers.Domain.Entities.Customer", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("DefaultBillingAddressId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("DefaultShippingAddressId")
                        .HasColumnType("uuid");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("uuid");

                    b.ComplexProperty<Dictionary<string, object>>("FirstName", "VertexCommerce.Modules.Customers.Domain.Entities.Customer.FirstName#FirstName", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasMaxLength(100)
                                .IsUnicode(true)
                                .HasColumnType("character varying(100)")
                                .HasColumnName("FirstName")
                                .IsFixedLength(false);
                        });

                    b.ComplexProperty<Dictionary<string, object>>("LastName", "VertexCommerce.Modules.Customers.Domain.Entities.Customer.LastName#LastName", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasMaxLength(100)
                                .IsUnicode(true)
                                .HasColumnType("character varying(100)")
                                .HasColumnName("LastName")
                                .IsFixedLength(false);
                        });

                    b.ComplexProperty<Dictionary<string, object>>("PhoneNumber", "VertexCommerce.Modules.Customers.Domain.Entities.Customer.PhoneNumber#PhoneNumber", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasMaxLength(20)
                                .IsUnicode(false)
                                .HasColumnType("character varying(20)")
                                .HasColumnName("PhoneNumber")
                                .IsFixedLength(false);
                        });

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("Customers", "customers");
                });

            modelBuilder.Entity("VertexCommerce.Modules.Customers.Domain.Entities.CustomerAddress", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("CustomerId")
                        .HasColumnType("uuid");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<string>("Label")
                        .HasMaxLength(50)
                        .IsUnicode(true)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("Label")
                        .IsFixedLength(false);

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.ComplexProperty<Dictionary<string, object>>("Address", "VertexCommerce.Modules.Customers.Domain.Entities.CustomerAddress.Address#Address", b1 =>
                        {
                            b1.IsRequired();

                            b1.ComplexProperty<Dictionary<string, object>>("City", "VertexCommerce.Modules.Customers.Domain.Entities.CustomerAddress.Address#Address.City#City", b2 =>
                                {
                                    b2.IsRequired();

                                    b2.Property<string>("Value")
                                        .IsRequired()
                                        .HasMaxLength(100)
                                        .IsUnicode(true)
                                        .HasColumnType("character varying(100)")
                                        .HasColumnName("City")
                                        .IsFixedLength(false);
                                });

                            b1.ComplexProperty<Dictionary<string, object>>("Location", "VertexCommerce.Modules.Customers.Domain.Entities.CustomerAddress.Address#Address.Location#GeoLocation", b2 =>
                                {
                                    b2.IsRequired();

                                    b2.Property<decimal>("Latitude")
                                        .HasPrecision(9, 6)
                                        .HasColumnType("numeric(9,6)")
                                        .HasColumnName("Latitude");

                                    b2.Property<decimal>("Longitude")
                                        .HasPrecision(9, 6)
                                        .HasColumnType("numeric(9,6)")
                                        .HasColumnName("Longitude");
                                });

                            b1.ComplexProperty<Dictionary<string, object>>("PostalAddress", "VertexCommerce.Modules.Customers.Domain.Entities.CustomerAddress.Address#Address.PostalAddress#PostalAddress", b2 =>
                                {
                                    b2.IsRequired();

                                    b2.Property<string>("Value")
                                        .IsRequired()
                                        .HasMaxLength(500)
                                        .IsUnicode(true)
                                        .HasColumnType("character varying(500)")
                                        .HasColumnName("PostalAddress")
                                        .IsFixedLength(false);
                                });

                            b1.ComplexProperty<Dictionary<string, object>>("PostalCode", "VertexCommerce.Modules.Customers.Domain.Entities.CustomerAddress.Address#Address.PostalCode#PostalCode", b2 =>
                                {
                                    b2.IsRequired();

                                    b2.Property<string>("Value")
                                        .IsRequired()
                                        .HasMaxLength(10)
                                        .IsUnicode(false)
                                        .HasColumnType("character varying(10)")
                                        .HasColumnName("PostalCode")
                                        .IsFixedLength(false);
                                });

                            b1.ComplexProperty<Dictionary<string, object>>("Province", "VertexCommerce.Modules.Customers.Domain.Entities.CustomerAddress.Address#Address.Province#Province", b2 =>
                                {
                                    b2.IsRequired();

                                    b2.Property<string>("Value")
                                        .IsRequired()
                                        .HasMaxLength(100)
                                        .IsUnicode(true)
                                        .HasColumnType("character varying(100)")
                                        .HasColumnName("Province")
                                        .IsFixedLength(false);
                                });
                        });

                    b.HasKey("Id");

                    b.HasIndex("CustomerId");

                    b.ToTable("CustomerAddresses", "customers");
                });

            modelBuilder.Entity("VertexCommerce.Modules.Customers.Domain.Entities.CustomerAddress", b =>
                {
                    b.HasOne("VertexCommerce.Modules.Customers.Domain.Entities.Customer", null)
                        .WithMany("Addresses")
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("VertexCommerce.Modules.Customers.Domain.Entities.Customer", b =>
                {
                    b.Navigation("Addresses");
                });
#pragma warning restore 612, 618
        }
    }
}
