// <auto-generated />
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using VertexCommerce.Modules.Catalog.Persistence.Postgres;

#nullable disable

namespace VertexCommerce.Modules.Catalog.Persistence.Postgres.Migrations
{
    [DbContext(typeof(CatalogDbContext))]
    [Migration("20260913111907_UpdateProductVariantReservedQuantity")]
    partial class UpdateProductVariantReservedQuantity
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("catalog")
                .HasAnnotation("ProductVersion", "9.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("VertexCommerce.Modules.Catalog.Domain.Categories.Category", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("IconPath")
                        .HasMaxLength(500)
                        .IsUnicode(true)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("icon_path")
                        .IsFixedLength(false);

                    b.Property<string>("ImageAltText")
                        .HasMaxLength(200)
                        .IsUnicode(true)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("image_alt_text")
                        .IsFixedLength(false);

                    b.Property<bool>("IncludeInMenu")
                        .HasColumnType("boolean")
                        .HasColumnName("include_in_menu");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<Guid?>("ParentId")
                        .HasColumnType("uuid")
                        .HasColumnName("parent_id");

                    b.Property<bool>("ShowOnHome")
                        .HasColumnType("boolean")
                        .HasColumnName("show_on_home");

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer")
                        .HasColumnName("sort_order");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.ComplexProperty<Dictionary<string, object>>("CoverImagePath", "VertexCommerce.Modules.Catalog.Domain.Categories.Category.CoverImagePath#ImagePath", b1 =>
                        {
                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasMaxLength(500)
                                .IsUnicode(true)
                                .HasColumnType("character varying(500)")
                                .HasColumnName("cover_image_path")
                                .IsFixedLength(false);
                        });

                    b.ComplexProperty<Dictionary<string, object>>("Description", "VertexCommerce.Modules.Catalog.Domain.Categories.Category.Description#CategoryDescription", b1 =>
                        {
                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasMaxLength(1000)
                                .IsUnicode(true)
                                .HasColumnType("character varying(1000)")
                                .HasColumnName("description")
                                .IsFixedLength(false);
                        });

                    b.ComplexProperty<Dictionary<string, object>>("Name", "VertexCommerce.Modules.Catalog.Domain.Categories.Category.Name#CategoryName", b1 =>
                        {
                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasMaxLength(100)
                                .IsUnicode(true)
                                .HasColumnType("character varying(100)")
                                .HasColumnName("name")
                                .IsFixedLength(false);
                        });

                    b.ComplexProperty<Dictionary<string, object>>("Seo", "VertexCommerce.Modules.Catalog.Domain.Categories.Category.Seo#SeoMetadata", b1 =>
                        {
                            b1.Property<string>("Keywords")
                                .HasMaxLength(500)
                                .HasColumnType("character varying(500)")
                                .HasColumnName("seo_keywords");

                            b1.Property<string>("MetaDescription")
                                .IsRequired()
                                .HasMaxLength(160)
                                .HasColumnType("character varying(160)")
                                .HasColumnName("seo_meta_description");

                            b1.Property<string>("MetaTitle")
                                .IsRequired()
                                .HasMaxLength(60)
                                .HasColumnType("character varying(60)")
                                .HasColumnName("seo_meta_title");

                            b1.Property<string>("Slug")
                                .IsRequired()
                                .HasMaxLength(200)
                                .HasColumnType("character varying(200)")
                                .HasColumnName("seo_slug");
                        });

                    b.HasKey("Id");

                    b.HasIndex("IsActive");

                    b.HasIndex("ParentId");

                    b.ToTable("categories", "catalog");
                });

            modelBuilder.Entity("VertexCommerce.Modules.Catalog.Domain.Medias.MediaFile", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime?>("ConfirmedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("confirmed_at");

                    b.Property<string>("ContentType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("content_type");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<string>("OriginalFileName")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)")
                        .HasColumnName("original_file_name");

                    b.Property<string>("RelativePath")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("relative_path");

                    b.Property<long>("SizeBytes")
                        .HasColumnType("bigint")
                        .HasColumnName("size_bytes");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("media_files", "catalog");
                });

            modelBuilder.Entity("VertexCommerce.Modules.Catalog.Domain.Products.CatalogAttribute", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(true)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("code")
                        .IsFixedLength(false);

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<string>("Type")
                        .HasMaxLength(50)
                        .IsUnicode(true)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("type")
                        .IsFixedLength(false);

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.ComplexProperty<Dictionary<string, object>>("DefaultName", "VertexCommerce.Modules.Catalog.Domain.Products.CatalogAttribute.DefaultName#AttributeName", b1 =>
                        {
                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasMaxLength(100)
                                .IsUnicode(true)
                                .HasColumnType("character varying(100)")
                                .HasColumnName("default_name")
                                .IsFixedLength(false);
                        });

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("catalog_attributes", "catalog");
                });

            modelBuilder.Entity("VertexCommerce.Modules.Catalog.Domain.Products.CatalogAttributeOption", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("AttributeId")
                        .HasColumnType("uuid")
                        .HasColumnName("attribute_id");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(true)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("code")
                        .IsFixedLength(false);

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<string>("MediaPath")
                        .HasMaxLength(500)
                        .IsUnicode(true)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("media_path")
                        .IsFixedLength(false);

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.ComplexProperty<Dictionary<string, object>>("DefaultName", "VertexCommerce.Modules.Catalog.Domain.Products.CatalogAttributeOption.DefaultName#OptionValue", b1 =>
                        {
                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasMaxLength(100)
                                .IsUnicode(true)
                                .HasColumnType("character varying(100)")
                                .HasColumnName("default_name")
                                .IsFixedLength(false);
                        });

                    b.HasKey("Id");

                    b.HasIndex("AttributeId", "Code")
                        .IsUnique();

                    b.ToTable("catalog_attribute_options", "catalog");
                });

            modelBuilder.Entity("VertexCommerce.Modules.Catalog.Domain.Products.Product", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("CategoryId")
                        .HasColumnType("uuid")
                        .HasColumnName("category_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Description")
                        .HasMaxLength(2000)
                        .IsUnicode(true)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("description")
                        .IsFixedLength(false);

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.ComplexProperty<Dictionary<string, object>>("Name", "VertexCommerce.Modules.Catalog.Domain.Products.Product.Name#ProductName", b1 =>
                        {
                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasMaxLength(200)
                                .IsUnicode(true)
                                .HasColumnType("character varying(200)")
                                .HasColumnName("name")
                                .IsFixedLength(false);
                        });

                    b.ComplexProperty<Dictionary<string, object>>("Seo", "VertexCommerce.Modules.Catalog.Domain.Products.Product.Seo#SeoMetadata", b1 =>
                        {
                            b1.Property<string>("Keywords")
                                .HasMaxLength(200)
                                .IsUnicode(true)
                                .HasColumnType("character varying(200)")
                                .HasColumnName("seo_keywords")
                                .IsFixedLength(false);

                            b1.Property<string>("MetaDescription")
                                .HasMaxLength(500)
                                .IsUnicode(true)
                                .HasColumnType("character varying(500)")
                                .HasColumnName("seo_meta_description")
                                .IsFixedLength(false);

                            b1.Property<string>("MetaTitle")
                                .HasMaxLength(150)
                                .IsUnicode(true)
                                .HasColumnType("character varying(150)")
                                .HasColumnName("seo_meta_title")
                                .IsFixedLength(false);

                            b1.Property<string>("Slug")
                                .IsRequired()
                                .HasMaxLength(255)
                                .IsUnicode(true)
                                .HasColumnType("character varying(255)")
                                .HasColumnName("seo_slug")
                                .IsFixedLength(false);
                        });

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.HasIndex("IsActive");

                    b.ToTable("products", "catalog");
                });

            modelBuilder.Entity("VertexCommerce.Modules.Catalog.Domain.Products.ProductVariant", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<Guid>("ProductId")
                        .HasColumnType("uuid");

                    b.Property<int>("ReservedQuantity")
                        .HasColumnType("integer");

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer");

                    b.Property<int>("StockQuantity")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.ComplexProperty<Dictionary<string, object>>("Price", "VertexCommerce.Modules.Catalog.Domain.Products.ProductVariant.Price#Money", b1 =>
                        {
                            b1.Property<decimal>("Amount")
                                .HasColumnType("numeric")
                                .HasColumnName("price_amount");

                            b1.Property<string>("Currency")
                                .IsRequired()
                                .HasMaxLength(3)
                                .IsUnicode(true)
                                .HasColumnType("character varying(3)")
                                .HasColumnName("price_currency")
                                .IsFixedLength(false);
                        });

                    b.ComplexProperty<Dictionary<string, object>>("Sku", "VertexCommerce.Modules.Catalog.Domain.Products.ProductVariant.Sku#Sku", b1 =>
                        {
                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasMaxLength(50)
                                .IsUnicode(true)
                                .HasColumnType("character varying(50)")
                                .HasColumnName("sku")
                                .IsFixedLength(false);
                        });

                    b.HasKey("Id");

                    b.HasIndex("ProductId");

                    b.ToTable("product_variants", "catalog");
                });

            modelBuilder.Entity("VertexCommerce.Shared.Persistence.Outbox.OutboxMessage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Error")
                        .HasColumnType("text");

                    b.Property<DateTime>("OccurredOn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("ProcessedOn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("RetryCount")
                        .HasColumnType("integer");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("OutboxMessages", "catalog");
                });

            modelBuilder.Entity("VertexCommerce.Modules.Catalog.Domain.Categories.Category", b =>
                {
                    b.HasOne("VertexCommerce.Modules.Catalog.Domain.Categories.Category", null)
                        .WithMany("Children")
                        .HasForeignKey("ParentId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("VertexCommerce.Modules.Catalog.Domain.Products.CatalogAttributeOption", b =>
                {
                    b.HasOne("VertexCommerce.Modules.Catalog.Domain.Products.CatalogAttribute", null)
                        .WithMany("Options")
                        .HasForeignKey("AttributeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("VertexCommerce.Modules.Catalog.Domain.Products.Product", b =>
                {
                    b.HasOne("VertexCommerce.Modules.Catalog.Domain.Categories.Category", "Category")
                        .WithMany("Products")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.OwnsMany("VertexCommerce.Modules.Catalog.Domain.ValueObjects.ProductMedia", "Media", b1 =>
                        {
                            b1.Property<Guid>("ProductId")
                                .HasColumnType("uuid");

                            b1.Property<int>("__synthesizedOrdinal")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("integer");

                            b1.Property<string>("AltText")
                                .HasColumnType("text")
                                .HasAnnotation("Relational:JsonPropertyName", "alt_text");

                            b1.Property<string>("AssociatedAttributeCode")
                                .HasColumnType("text")
                                .HasAnnotation("Relational:JsonPropertyName", "associated_attribute_code");

                            b1.Property<string>("AssociatedOptionCode")
                                .HasColumnType("text")
                                .HasAnnotation("Relational:JsonPropertyName", "associated_option_code");

                            b1.Property<string>("Path")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasAnnotation("Relational:JsonPropertyName", "media_path");

                            b1.Property<int>("SortOrder")
                                .HasColumnType("integer")
                                .HasAnnotation("Relational:JsonPropertyName", "sort_order");

                            b1.Property<int>("Type")
                                .HasColumnType("integer")
                                .HasAnnotation("Relational:JsonPropertyName", "media_type");

                            b1.HasKey("ProductId", "__synthesizedOrdinal");

                            b1.ToTable("products", "catalog");

                            b1.ToJson("Media");

                            b1.WithOwner()
                                .HasForeignKey("ProductId");
                        });

                    b.Navigation("Category");

                    b.Navigation("Media");
                });

            modelBuilder.Entity("VertexCommerce.Modules.Catalog.Domain.Products.ProductVariant", b =>
                {
                    b.HasOne("VertexCommerce.Modules.Catalog.Domain.Products.Product", null)
                        .WithMany("Variants")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsMany("VertexCommerce.Modules.Catalog.Domain.ValueObjects.ProductAttribute", "Attributes", b1 =>
                        {
                            b1.Property<Guid>("ProductVariantId")
                                .HasColumnType("uuid");

                            b1.Property<int>("__synthesizedOrdinal")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("integer");

                            b1.Property<string>("AttributeCode")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasAnnotation("Relational:JsonPropertyName", "attribute_code");

                            b1.Property<string>("OptionCode")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasAnnotation("Relational:JsonPropertyName", "option_code");

                            b1.HasKey("ProductVariantId", "__synthesizedOrdinal");

                            b1.ToTable("product_variants", "catalog");

                            b1.ToJson("Attributes");

                            b1.WithOwner()
                                .HasForeignKey("ProductVariantId");
                        });

                    b.Navigation("Attributes");
                });

            modelBuilder.Entity("VertexCommerce.Modules.Catalog.Domain.Categories.Category", b =>
                {
                    b.Navigation("Children");

                    b.Navigation("Products");
                });

            modelBuilder.Entity("VertexCommerce.Modules.Catalog.Domain.Products.CatalogAttribute", b =>
                {
                    b.Navigation("Options");
                });

            modelBuilder.Entity("VertexCommerce.Modules.Catalog.Domain.Products.Product", b =>
                {
                    b.Navigation("Variants");
                });
#pragma warning restore 612, 618
        }
    }
}
