// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using VertexCommerce.Modules.Notifications.Persistence;

#nullable disable

namespace VertexCommerce.Modules.Notifications.Persistence.Migrations;

[DbContext(typeof(NotificationsDbContext))]
[Migration("20260920090000_InitialNotifications")]
partial class InitialNotifications
{
    /// <inheritdoc />
    protected override void BuildTargetModel(ModelBuilder modelBuilder)
    {
#pragma warning disable 612, 618
        modelBuilder
            .HasDefaultSchema("notifications")
            .HasAnnotation("ProductVersion", "9.0.4")
            .HasAnnotation("Relational:MaxIdentifierLength", 63);

        NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

        modelBuilder.Entity("VertexCommerce.Modules.Notifications.Domain.Entities.Notification", b =>
            {
                b.Property<Guid>("Id")
                    .HasColumnType("uuid");

                b.Property<DateTime>("CreatedAt")
                    .HasColumnType("timestamp with time zone");

                b.Property<bool>("IsRead")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("boolean")
                    .HasDefaultValue(false);

                b.Property<string>("Message")
                    .IsRequired()
                    .HasMaxLength(1000)
                    .HasColumnType("character varying(1000)");

                b.Property<string>("PayloadJson")
                    .HasMaxLength(2000)
                    .HasColumnType("character varying(2000)");

                b.Property<DateTime?>("ReadAt")
                    .HasColumnType("timestamp with time zone");

                b.Property<string>("Title")
                    .IsRequired()
                    .HasMaxLength(256)
                    .HasColumnType("character varying(256)");

                b.Property<string>("Type")
                    .IsRequired()
                    .HasMaxLength(64)
                    .HasColumnType("character varying(64)");

                b.Property<Guid>("UserId")
                    .HasColumnType("uuid");

                b.HasKey("Id");

                b.HasIndex("UserId", "CreatedAt");

                b.HasIndex("UserId", "IsRead");

                b.ToTable("Notifications", "notifications");
            });

        modelBuilder.Entity("VertexCommerce.Modules.Notifications.Domain.Entities.PushSubscription", b =>
            {
                b.Property<Guid>("Id")
                    .HasColumnType("uuid");

                b.Property<string>("AuthKey")
                    .IsRequired()
                    .HasMaxLength(128)
                    .HasColumnType("character varying(128)");

                b.Property<DateTime>("CreatedAt")
                    .HasColumnType("timestamp with time zone");

                b.Property<string>("Endpoint")
                    .IsRequired()
                    .HasMaxLength(2048)
                    .HasColumnType("character varying(2048)");

                b.Property<string>("P256dhKey")
                    .IsRequired()
                    .HasMaxLength(256)
                    .HasColumnType("character varying(256)");

                b.Property<string>("UserAgent")
                    .HasMaxLength(512)
                    .HasColumnType("character varying(512)");

                b.Property<Guid>("UserId")
                    .HasColumnType("uuid");

                b.HasKey("Id");

                b.HasIndex("Endpoint")
                    .IsUnique();

                b.HasIndex("UserId");

                b.ToTable("PushSubscriptions", "notifications");
            });
#pragma warning restore 612, 618
    }
}
