<Project Sdk="Microsoft.NET.Sdk.Web">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <Nullable>enable</Nullable>
        <ImplicitUsings>enable</ImplicitUsings>
    </PropertyGroup>

    <ItemGroup>
      <PackageReference Include="HotChocolate.AspNetCore" />
      <PackageReference Include="HotChocolate.Data" />
      <PackageReference Include="HotChocolate.Types" />
      <PackageReference Include="Microsoft.EntityFrameworkCore.Design">
        <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
        <PrivateAssets>all</PrivateAssets>
      </PackageReference>
      <ProjectReference Include="..\VertexCommerce.Modules.Catalog\VertexCommerce.Modules.Catalog.csproj" />
      <ProjectReference Include="..\VertexCommerce.Modules.Orders\VertexCommerce.Modules.Orders.csproj" />
      <ProjectReference Include="..\VertexCommerce.Modules.Basket\VertexCommerce.Modules.Basket.csproj" />
      <ProjectReference Include="..\VertexCommerce.Modules.Customers\VertexCommerce.Modules.Customers.csproj" />
      <ProjectReference Include="..\VertexCommerce.Modules.Identity\VertexCommerce.Modules.Identity.csproj" />
    </ItemGroup>

    <ItemGroup>
      <PackageReference Include="Microsoft.AspNetCore.OpenApi" />
      <PackageReference Include="Serilog.AspNetCore" />
      <PackageReference Include="Scalar.AspNetCore" />
      <PackageReference Include="Swashbuckle.AspNetCore" />
    </ItemGroup>

    <ItemGroup>
      <Folder Include="GraphQL\Common\" />
    </ItemGroup>

</Project>
