<Project Sdk="Microsoft.NET.Sdk">

    <ItemGroup>
      <ProjectReference Include="..\VertexCommerce.Shared\VertexCommerce.Shared.csproj" />
    </ItemGroup>
    <PropertyGroup>
        <NuGetAudit>false</NuGetAudit>
    </PropertyGroup>


    <ItemGroup>
      <PackageReference Include="Microsoft.Extensions.Options.ConfigurationExtensions" />
      <PackageReference Include="HotChocolate.AspNetCore" />
      <PackageReference Include="HotChocolate.Data" />
      <PackageReference Include="HotChocolate.Types" />
      <PackageReference Include="MongoDB.Driver" />
      <PackageReference Include="HotChocolate.Data.MongoDb" />
    </ItemGroup>


    <ItemGroup>
      <Folder Include="Domain\Repositories\" />
    </ItemGroup>

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <LangVersion>14</LangVersion>
        <ImplicitUsings>disable</ImplicitUsings>
        <Nullable>enable</Nullable>
    </PropertyGroup>

</Project>
